### ISSUE TITLE
output results

### ISSUE THREAD

**Issue by jinalee-mech** [shiftlab-nanodrone/sparse-gslam#3]
After I ran roslaunch stanford-gates successfully, I got those result maps(landmark and pose graph) and four files. (.btime/.dtime/.ftime/.result)
![image](https://user-images.githubusercontent.com/90688988/218976476-fd2764c1-509d-46b0-aeb5-953233ce5c0e.png)

I think landmark map(left) was built successfully, but pose graph(right) seems quite different with pose graph in the paper. 
Are these the right outputs?

**Comment by hanzhi713** [comment]
The rviz configs in the repository don't have the displays properly checked, probably due to my experiments before the last git push. I don't have my laptop with me right now, but you can check the slam_map in the `Displays` on the left, and it should be the one that displays the whole map. There are also other useful markers that you can check out.

**Comment by jinalee-mech** [comment]
Solved it. Thanks!
